spring.datasource.url=jdbc:mysql://localhost:3306/r2sshop_db\
  ?rewriteBatchedStatements=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver